import { useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "./ui/dialog";
import { Button } from "./ui/button";
import { Badge } from "./ui/badge";
import { ScrollArea } from "./ui/scroll-area";
import { X, Calendar, ExternalLink, Archive, Heart, Sparkles, FileText, Bot } from "lucide-react";

interface Article {
  id: string;
  title: string;
  summary: string;
  source: string;
  category: string;
  publishedAt: string;
  url: string;
  content?: string;
}

interface ArticleReaderProps {
  article: Article | null;
  isOpen: boolean;
  onClose: () => void;
  onArchive: (id: string) => void;
  onFavorite: (id: string) => void;
  isArchived: boolean;
  isFavorited: boolean;
}

type ViewMode = 'article' | 'summary';

export function ArticleReader({ 
  article, 
  isOpen, 
  onClose, 
  onArchive, 
  onFavorite, 
  isArchived, 
  isFavorited 
}: ArticleReaderProps) {
  const [articleAiSummaries, setArticleAiSummaries] = useState<Map<string, string>>(new Map());
  const [generatingAiSummary, setGeneratingAiSummary] = useState<string | null>(null);
  const [viewMode, setViewMode] = useState<ViewMode>('article');

  if (!article) return null;

  const currentAiSummary = articleAiSummaries.get(article.id);
  const isGenerating = generatingAiSummary === article.id;

  const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', { 
      weekday: 'long',
      year: 'numeric',
      month: 'long', 
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  const handleExternalLink = () => {
    window.open(article.url, '_blank', 'noopener,noreferrer');
  };

  const handleGenerateAiSummary = async () => {
    setGeneratingAiSummary(article.id);
    
    // Simulate AI summary generation
    await new Promise(resolve => setTimeout(resolve, 3000));

    // Generate mock AI summary based on article content
    const mockSummary = `**AI Summary**

**Key Points:**
- ${article.title.split(' ').slice(0, 8).join(' ')} represents a significant development in ${article.category.toLowerCase()}
- The article from ${article.source} highlights several important implications for the industry
- Key stakeholders and market participants should pay attention to these emerging trends

**Main Takeaways:**
${article.summary.split('.').slice(0, 2).join('. ')}.

**Analysis:**
This development is particularly noteworthy because it aligns with broader trends we've been tracking in the ${article.category.toLowerCase()} sector. The implications extend beyond immediate market reactions and could influence policy decisions in the coming months.

**Conclusion:**
Based on the article content and current market context, this story represents an important data point for understanding the evolving landscape. Readers should consider the broader implications while staying informed about subsequent developments.

*This summary was generated by AI and represents key insights from the original article.*`;

    setArticleAiSummaries(prev => new Map(prev).set(article.id, mockSummary));
    setGeneratingAiSummary(null);
    setViewMode('summary');
  };

  const processedContent = article.content ? (() => {
    const paragraphs = article.content.split('\n\n');
    const result = [];
    let listItems = [];
    
    paragraphs.forEach((paragraph, index) => {
      if (paragraph.startsWith('- ')) {
        listItems.push(paragraph.slice(2));
      } else {
        if (listItems.length > 0) {
          result.push(
            <ul key={`list-${index}`} className="mb-4 ml-4">
              {listItems.map((item, itemIndex) => (
                <li key={itemIndex} className="mb-2 list-disc leading-relaxed">
                  {item.includes('**') ? (
                    <>
                      {item.split(/\*\*(.*?)\*\*/g).map((part, partIndex) => (
                        partIndex % 2 === 1 ? (
                          <strong key={partIndex} className="font-medium">{part}</strong>
                        ) : (
                          part
                        )
                      ))}
                    </>
                  ) : (
                    item
                  )}
                </li>
              ))}
            </ul>
          );
          listItems = [];
        }
        
        if (paragraph.startsWith('**') && paragraph.endsWith('**')) {
          result.push(
            <h3 key={index} className="font-serif font-medium mb-3 mt-6 first:mt-0">
              {paragraph.slice(2, -2)}
            </h3>
          );
        } else if (paragraph.includes('**')) {
          const parts = paragraph.split(/\*\*(.*?)\*\*/g);
          result.push(
            <p key={index} className="mb-4 leading-relaxed">
              {parts.map((part, partIndex) => (
                partIndex % 2 === 1 ? (
                  <strong key={partIndex} className="font-medium">{part}</strong>
                ) : (
                  part
                )
              ))}
            </p>
          );
        } else if (paragraph.trim()) {
          result.push(
            <p key={index} className="mb-4 leading-relaxed">
              {paragraph}
            </p>
          );
        }
      }
    });
    
    // Handle any remaining list items
    if (listItems.length > 0) {
      result.push(
        <ul key="final-list" className="mb-4 ml-4">
          {listItems.map((item, itemIndex) => (
            <li key={itemIndex} className="mb-2 list-disc leading-relaxed">
              {item}
            </li>
          ))}
        </ul>
      );
    }
    
    return result;
  })() : null;

  const processedAiSummary = currentAiSummary ? (() => {
    const paragraphs = currentAiSummary.split('\n\n');
    return paragraphs.map((paragraph, index) => {
      if (paragraph.startsWith('**') && paragraph.endsWith('**')) {
        return (
          <h3 key={index} className="font-serif font-medium mb-3 mt-6 first:mt-0">
            {paragraph.slice(2, -2)}
          </h3>
        );
      } else if (paragraph.includes('**')) {
        const parts = paragraph.split(/\*\*(.*?)\*\*/g);
        return (
          <p key={index} className="mb-4 leading-relaxed">
            {parts.map((part, partIndex) => (
              partIndex % 2 === 1 ? (
                <strong key={partIndex} className="font-medium">{part}</strong>
              ) : (
                part
              )
            ))}
          </p>
        );
      } else if (paragraph.startsWith('- ')) {
        return (
          <p key={index} className="mb-2 ml-4 leading-relaxed">
            • {paragraph.slice(2)}
          </p>
        );
      } else if (paragraph.startsWith('*') && paragraph.endsWith('*')) {
        return (
          <p key={index} className="mb-4 text-sm text-muted-foreground italic">
            {paragraph.slice(1, -1)}
          </p>
        );
      } else if (paragraph.trim()) {
        return (
          <p key={index} className="mb-4 leading-relaxed">
            {paragraph}
          </p>
        );
      }
      return null;
    }).filter(Boolean);
  })() : null;

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="w-full h-full max-w-none max-h-none m-0 p-0 bg-background rounded-none border-0 [&>button]:hidden">
        <div className="flex flex-col h-full">
          {/* Header */}
          <DialogHeader className="flex-shrink-0 p-4 border-b border-border">
            <div className="flex items-center justify-between mb-4">
              <Button
                variant="ghost"
                size="icon"
                onClick={onClose}
                className="h-8 w-8"
              >
                <X className="h-4 w-4" />
              </Button>
              
              <div className="flex items-center gap-2">
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => onFavorite(article.id)}
                  className="h-8 w-8 p-0"
                >
                  <Heart 
                    className={`h-4 w-4 ${isFavorited ? 'fill-red-500 text-red-500' : 'text-muted-foreground'}`} 
                  />
                </Button>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleExternalLink}
                  className="h-8 w-8 p-0"
                >
                  <ExternalLink className="h-4 w-4 text-muted-foreground" />
                </Button>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => onArchive(article.id)}
                  className="h-8 w-8 p-0"
                >
                  <Archive 
                    className={`h-4 w-4 ${isArchived ? 'fill-current text-primary' : 'text-muted-foreground'}`} 
                  />
                </Button>
              </div>
            </div>
            
            <div className="flex items-center gap-2 mb-3">
              <Badge variant="secondary" className="text-xs px-2 py-0.5">
                {article.category}
              </Badge>
              <span className="text-sm text-muted-foreground">
                {article.source}
              </span>
            </div>
            
            <DialogTitle className="text-left font-serif leading-tight mb-3">
              {article.title}
            </DialogTitle>
            
            <DialogDescription className="sr-only">
              Article from {article.source} in {article.category} category, published {formatDate(article.publishedAt)}
            </DialogDescription>
            
            <div className="flex items-center gap-1 text-xs text-muted-foreground mb-4">
              <Calendar className="h-3 w-3" />
              <span>Published {formatDate(article.publishedAt)}</span>
            </div>

            {/* Action Buttons */}
            <div className="flex items-center gap-2">
              {!currentAiSummary && !isGenerating && (
                <Button
                  variant="outline"
                  size="sm"
                  onClick={handleGenerateAiSummary}
                  className="h-8 px-3 text-xs font-medium"
                >
                  <Sparkles className="w-3 h-3 mr-1" />
                  Create AI Summary
                </Button>
              )}
              
              {isGenerating && (
                <Button
                  variant="outline"
                  size="sm"
                  disabled
                  className="h-8 px-3 text-xs font-medium"
                >
                  <Sparkles className="w-3 h-3 mr-1 animate-pulse" />
                  Generating...
                </Button>
              )}
              
              {(currentAiSummary || isGenerating) && (
                <>
                  <Button
                    variant={viewMode === 'article' ? 'default' : 'outline'}
                    size="sm"
                    onClick={() => setViewMode('article')}
                    className="h-8 px-3 text-xs font-medium"
                  >
                    <FileText className="w-3 h-3 mr-1" />
                    Read Article
                  </Button>
                  
                  {currentAiSummary && (
                    <Button
                      variant={viewMode === 'summary' ? 'default' : 'outline'}
                      size="sm"
                      onClick={() => setViewMode('summary')}
                      className="h-8 px-3 text-xs font-medium"
                    >
                      <Bot className="w-3 h-3 mr-1" />
                      Read AI Summary
                    </Button>
                  )}
                </>
              )}
            </div>
          </DialogHeader>
          
          {/* Content */}
          <ScrollArea className="flex-1">
            <div className="p-4">
              {viewMode === 'article' ? (
                <>
                  <p className="text-muted-foreground mb-6 leading-relaxed">
                    {article.summary}
                  </p>
                  
                  {article.content ? (
                    <div className="prose prose-sm max-w-none">
                      {processedContent}
                    </div>
                  ) : (
                    <div className="text-center py-8 text-muted-foreground">
                      <p>Full article content would be loaded here from the RSS feed or newsletter source.</p>
                      <Button
                        variant="outline"
                        onClick={handleExternalLink}
                        className="mt-4"
                      >
                        <ExternalLink className="w-4 h-4 mr-2" />
                        Read Full Article
                      </Button>
                    </div>
                  )}
                </>
              ) : viewMode === 'summary' && currentAiSummary ? (
                <div className="prose prose-sm max-w-none">
                  {processedAiSummary}
                </div>
              ) : isGenerating ? (
                <div className="text-center py-8 text-muted-foreground">
                  <Sparkles className="w-8 h-8 mx-auto mb-4 animate-pulse text-primary" />
                  <p>Generating AI summary...</p>
                  <p className="text-sm mt-2">Analyzing article content and creating key insights.</p>
                </div>
              ) : null}
            </div>
          </ScrollArea>
        </div>
      </DialogContent>
    </Dialog>
  );
}